### ISSUE TITLE
[WIP] Jobs Version 1.0.0 Release Notes

### ISSUE THREAD

**Issue by XL19860214** [Xuwei-Li/li.xuwei.jobs#1]
# Tasks
* [x] 1. Set Initiatives for Jobs Version 1.0.0
* [x] 2. Sprint Planning for Jobs Version 0.1.0
* [x] 3. [Sprint-1] Start Sprint for Jobs Version 0.1.0
* [x] 4. [Sprint-2] ]Sprint again for Jobs Version 0.1.0 by completing unfinished tasks in Sprint-1

### 1. Set Initiatives for Jobs Version 1.0.0

<details><summary>Details</summary>

1. Include general information of job occupations that cover over 50% population on the planet Earth.
2. Introduce industrial experts within and around main content.
3. Provide job description templates for Hiring Manager (HR).
4. Include candidate qualification verification for HR.
5. Provide job resume templates for Job Applicant / Job Candidate (Labor).
6. Include job occupation qualification details for Labor.

----------------------------------------
</details>

### 2. Sprint Planning for Jobs Version 0.1.0

<details><summary>Details</summary>

1. Import Sprint Template: Fixed Achievement Sprint
1.1. Sprint Period Limit: 48 Hours
1.2. Sprint Goal: Basic Homepage with links to Cashier, Web Developer, Web Designer careers.
2. Epics
2.1. Create basic Homepage with links to defined jobs. #2
2.2. Create job profile for Cashier. #3
2.3. Create job profile for Web Designer. #4
2.4. Create job profile for Web Developer. #5

----------------------------------------
</details>

### 3. [Sprint-1] Start Sprint for Jobs Version 0.1.0
**Start** UTC+8 202201221625
**Estimated End** UTC+8 202201241625

<details><summary>Details</summary>

⚡ Conclusion
-------------

Only finish Story #6 of #2 in this sprint.

----------------------------------------
</details>

### 4. [Sprint-2] Sprint again for Jobs Version 0.1.0 by completing unfinished tasks in Sprint-1
**Start** UTC+8 202201241900
**Estimated End** UTC+8 202201261900

⚡ Conclusion
-------------

Achieve nothing. Do something else first.

----------------------------------------
</details>
