### ISSUE TITLE
[Designer] Prototype the Basic Homepage by Sketch Mac App

### ISSUE THREAD

**Issue by XL19860214** [Xuwei-Li/li.xuwei.jobs#6]
From #2
--------

# Summary
Use [Sketch Mac App](https://www.sketch.com) to prototype the homepage for Jobs Version 0.1.0.

# Tasks
* [x] 1. Collect all the usable display resolutions for [Sketch Artboard](https://www.sketch.com/docs/designing/the-interface/the-canvas/#how-to-use-artboards).
* [x] 2. Decide layout for the homepage prototype design. <sub>202201231600 -> 202201231703</sub>
* [x] 3. Figure out required components to fit each layout area. <sub>202201231706 -> 202201240136</sub>
* [x] 4. Deliver the final prototype design for the homepage of Jobs Version 0.1.0. <sub> 202201240136 -> 202201240239</sub>

## 1. Collect all the usable display resolutions for Sketch Artboard.

<details><summary>details</summary>

1. https://www.theverge.com/2021/9/24/22691187/2021-m1x-macbook-pro-screen-resolution-3456-x-2234-retina-3024-x-1964
1.1. 16-inch MacBook Pro: 3072x1920
1.2. 13-inch MacBook Pro: 2560x1600
2. https://www.gsmarena.com/glossary.php3?term=resolution
2.1. https://en.wikipedia.org/wiki/8K_resolution
2.2. https://en.wikipedia.org/wiki/16K_resolution
2.3. https://en.wikipedia.org/wiki/5K_resolution
2.4. https://en.wikipedia.org/wiki/10K_resolution

| Name | Resolution |
| -- | -- |
| Classic | 1024 x 768 |
| High Definition (HD) | 1280 x 720 |
| Full HD, FHD | 1920 x 1080 |
| 2K, Quad HD, QHD | 2560 x 1440 |
| 4K, Ultra HD | 3840 x 2160 |
| 8K UHD | 7680 × 4320 |
| 16K | 15360 × 8640 |
| 5K | 5120 × 2880 |
| 10K | 10240 × 4320 |

3. Sketch App Built-in
3.1. Desktop 1024 x 1024
3.2. Desktop HD 1440 x 1024

⚡ Conclusion
-------------
Use built-in resolutions for Artboard until better benefits for using other resolutions to be seen.

----------------------------------------
</details>

## 2. Decide layout for the homepage prototype design.

<details><summary>details</summary>

1. https://github.com/v4ex/WORKLOGS/wiki/Web-App-Design

⚡ Conclusion
-------------

<details><summary>For next version with more content.</summary>

![li.xuwei.jobs_Layout](https://user-images.githubusercontent.com/72472538/150706310-eb1e6fdc-a47a-49b1-92ac-4126db323529.png)

</details>

![li.xuwei.jobs_Layout2](https://user-images.githubusercontent.com/72472538/150749583-337f3ceb-2fa6-47d1-9847-14ce59c73447.png)

----------------------------------------
</details>

## 3. Figure out required components to fit each layout area.

<details><summary>details</summary>

1. https://github.com/v4ex/WORKLOGS/wiki/Web-App-Design
1.1. https://budibase.com/blog/5-examples-of-web-application-design/
1.2. https://bufferapp.github.io/ui/
2. https://github.com/airbnb/react-sketchapp
3. https://www.google.com/search?q=react+ui+components
3.1. https://mui.com
3.1.1. https://material-ui.com/store/items/sketch-react/
3.2. https://material.io
3.3. https://retool.com/blog/react-component-libraries/
3.4. https://github.com/react-bootstrap/react-bootstrap
3.4.1. https://github.com/react-bootstrap
3.4.2. https://react-bootstrap.github.io
3.5. https://ant.design
4. https://www.google.com/search?q=react+bootstrap+components
5. Use these:
5.1. 👍🏻 Use https://developer.apple.com/fonts/
5.2. 👍🏻 Use https://getbootstrap.com
5.3. 👍🏻 Use https://reactjs.org
5.4. 👍🏻 Use https://react-bootstrap.github.io
5.5. 👍🏻 Use https://themeselection.com/products/free-sketch-bootstrap-ui-kit/https://github.com/react-bootstrap/react-bootstrap

⚡ Conclusion
-------------

1. Required components
1.1. Homepage component 
1.2. HeaderBrand component
1.3. LinkToJob component
1.4. Footer component
2. Prototype

![li.xuwei.jobs_Prototype](https://user-images.githubusercontent.com/72472538/150757428-182c17ee-8f1d-4743-9787-56d1e12cac74.png)

----------------------------------------
</details>

## 4. Deliver the final prototype design for the homepage of Jobs Version 0.1.0.

![li xuwei jobs Homepage Design](https://user-images.githubusercontent.com/72472538/150767905-c5fe782e-fba6-4c70-bb31-c2f6003f1cee.png)

----------------------------------------
